name: End-to-End Tests
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python setup.py install
          sail --version
      - shell: bash
        env:
          SAIL_PROVIDER_TOKEN: ${{ secrets.SAIL_PROVIDER_TOKEN }}
          SAIL_API_BASE: https://sailed.io/api/1.0
        run: |
          sail config provider-token $SAIL_PROVIDER_TOKEN
          sail config email kovshenin@gmail.com
          python sail/tests/end2end.py
